-- Create Drones table
CREATE TABLE IF NOT EXISTS DRONES (
    "ID" BIGINT PRIMARY KEY AUTO_INCREMENT,
    "SERIAL_NUMBER" VARCHAR(100) NOT NULL,
    "MODEL" VARCHAR(100) NOT NULL,
    "BATTERY_CAPACITY" DECIMAL(5,2) NOT NULL,
    "STATE" VARCHAR(50) NOT NULL
);

-- Create Medication table with foreign key to Drones (one-to-many)
CREATE TABLE IF NOT EXISTS MEDICATION (
    "ID" BIGINT PRIMARY KEY AUTO_INCREMENT,
    "MEDICATION_NAME" VARCHAR(255) NOT NULL,
    "WEIGHT" DECIMAL(5,2) NOT NULL,
    "CODE" VARCHAR(100) UNIQUE NOT NULL,
    "IMAGE" BLOB,
    "DRONE_ID" BIGINT,
    FOREIGN KEY ("DRONE_ID") REFERENCES Drones("ID") ON DELETE CASCADE
);
